services:
  db:
    build: ./osm-postgis
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./data/:/data/
      - ./tmp/:/data/tmp/
  tiles:
    build: ./tiles
    ports:
      - "8080:80"

volumes:
  pg_data: