services:
  routy:
    build:
      context: .
      dockerfile: Dockerfile.graphhopper
    ports:
      - "8989:8989"
      - "8990:8990"
  tiles:
    image: overv/openstreetmap-tile-server
    volumes:
      - ./data/sweden-latest.osm.pbf:/data/region.osm.pbf
      - ./data/sweden.poly:/data/region.poly
      - tiles-db:/data/database/
      - tiles-tiles:/data/tiles/
    ports:
      - "8080:80"
    command: "run"
  pmtiles:
    build:
      context: .
      dockerfile: Dockerfile.pmtiles
    ports:
      - "8181:8181"

volumes:
  tiles-db:
  tiles-tiles:
